#!/usr/bin/env python3
"""Bundle data/*.json into assets/js/data-bundle.js as window.DB.
Each DB key can be fed by SEVERAL files (base + *-extra*) which are concatenated
and de-duplicated (by id, and by normalized name for people/brands).
Run after editing any data file:  python3 build_bundle.py
"""
import json, pathlib, re

ROOT = pathlib.Path(__file__).parent
DATA = ROOT / "data"
OUT = ROOT / "assets" / "js" / "data-bundle.js"

# key -> list of files (in priority order; earlier wins on dup)
FILES = {
    "brands": ["brands.json"],
    "licenses": ["licenses.json"],
    "influencers": ["influencers.json", "influencers-extra1.json", "influencers-extra2.json", "influencers-extra3.json"],
    "artists": ["artists.json"],
    "collaborations": ["collaborations.json", "collaborations-extra.json", "collaborations-extra2.json"],
    "benchmarks": ["benchmarks.json"],
    "platforms": ["platforms.json"],
    "sebAudit": ["seb-audit.json"],
    "sebAnalysis": ["seb-analysis.json"],
    "lexicon": ["lexicon.json"],
    "questions": ["questions.json"],
    "focus": ["focus.json"],
    "sources": ["sources.json"],
}
NAME_DEDUP = {"influencers", "brands"}  # also dedupe by normalized name


def norm_name(s):
    s = (s or "").lower()
    s = re.split(r"[(/]", s)[0]
    s = re.sub(r"[^a-z0-9À-ſ ]", "", s)
    return s.strip()


db = {}
for key, files in FILES.items():
    merged, seen_id, seen_name = [], set(), set()
    for fname in files:
        p = DATA / fname
        if not p.exists():
            continue
        data = json.loads(p.read_text(encoding="utf-8"))
        if not isinstance(data, list):
            db[key] = data
            break
        for row in data:
            rid = row.get("id")
            if rid and rid in seen_id:
                continue
            if key in NAME_DEDUP:
                nn = norm_name(row.get("name"))
                if nn and nn in seen_name:
                    continue
                seen_name.add(nn)
            if rid:
                seen_id.add(rid)
            merged.append(row)
    else:
        db[key] = merged
    n = len(db[key]) if isinstance(db[key], list) else "obj"
    print(f"  DB.{key:14s} {n}")

OUT.parent.mkdir(parents=True, exist_ok=True)
with open(OUT, "w", encoding="utf-8") as f:
    f.write("/* AUTO-GENERATED by build_bundle.py — do not edit by hand. */\n")
    f.write("window.DB = ")
    json.dump(db, f, ensure_ascii=False, separators=(",", ":"))
    f.write(";\n")
print(f"\nWrote {OUT} ({OUT.stat().st_size//1024} KB)")
